---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: avangrid-front-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/mkozub/avangrid-front
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: avangrid-front-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/kabanero/quote-frontend:tkn

